@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsaXNhaWQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MTM3MzMzNzksImV4cCI6MTYxMzczMzk3OX0.2uiZa6h4X_47iyQpQ8WYfdqVnlcX4EsXLO2vCJGHb2c

###
// student
GET http://a73fe3d26175b4b888af10f9d4d1912f-1288631366.us-east-1.elb.amazonaws.com/api/v1/student
token: {{authToken}}

###

GET http://a73fe3d26175b4b888af10f9d4d1912f-1288631366.us-east-1.elb.amazonaws.com/api/v1/student/18
token: {{authToken}}

###

POST http://a73fe3d26175b4b888af10f9d4d1912f-1288631366.us-east-1.elb.amazonaws.com/api/v1/student
token: {{authToken}}
Content-Type: application/json

{
    "name":"Miftakh Ali Said",
    "absent": 18
}

###

PATCH  http://a73fe3d26175b4b888af10f9d4d1912f-1288631366.us-east-1.elb.amazonaws.com/api/v1/student/18
token: {{authToken}}
Content-Type: application/json

{
    "name":"Miftakh Ali Said",
    "absent": 17
}

###

DELETE http://a73fe3d26175b4b888af10f9d4d1912f-1288631366.us-east-1.elb.amazonaws.com/api/v1/student/16
token: {{authToken}}

###
// user

POST http://a73fe3d26175b4b888af10f9d4d1912f-1288631366.us-east-1.elb.amazonaws.com/api/v1/user/register
Content-Type: application/json

{
    "username":"alisaid",
    "password":"123",
    "role":"admin"
}

###

POST http://a73fe3d26175b4b888af10f9d4d1912f-1288631366.us-east-1.elb.amazonaws.com/api/v1/user/login
Content-Type: application/json

{
    "username":"alisaid",
    "password":"123"
}

###

POST http://192.168.49.2:30172/api/v1/user/refreshtoken
Content-Type: application/json

{
    "refreshtoken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmE4NjkyYzMxMWI0MzM5ZDQyODY3YyIsImlhdCI6MTYxMzQwNTg2N30.3r4zRRM0d0efKFmgmllC0QhotEFxQMr5x1VQTslk6uM"
}